### ISSUE TITLE
Please provide trained weights

### ISSUE THREAD

**Issue by shubham12tomar** [amaljoseph/Signature-Verification_System_using_YOLOv5-and-CycleGAN#1]
Can you please provide trained weights for direct inference.

Thanks

**Comment by Giorgi-Sekhniashvili** [comment]
Hi, is there any updates on this issue or maybe a work in progress? What should we expect?

**Comment by muladzevitali** [comment]
Will be any updates available to the project?

**Comment by amaljoseph** [comment]
I have added the trained weights and data I have used [here](https://drive.google.com/drive/folders/1397Q9nqMqEsSesB9UvlIL1u1IGzrUOIK?usp=sharing).

**Comment by Hudahamedr** [comment]
Can you please provide

 The application would be made available for testing over [here]

**Comment by Hudahamedr** [comment]
Hi, is there any updates on this issue or maybe a work in progress? What should we expect?
thanks.
